name: Flutter CI

on:
  push:
  pull_request:
jobs:
  flutter-ci:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # specify the Flutter version (e.g., 'stable', 'beta', or a specific version)

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Analyze the code
      - name: Analyze code
        run: flutter analyze

      # Step 5: Run unit tests
      - name: Run tests
        run: flutter test

      # Step 6: Build the project (check if the project can be built)
      - name: Build the project
        run: flutter build apk --release # You can change this to other build commands (e.g., flutter build ios)

      # Optional: Upload the build artifact
      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/app-release.apk  # Modify the path based on your target platform
